# Generated by Django 2.2.1 on 2019-05-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_approved',
        ),
    ]
