# Generated by Django 2.2.1 on 2019-05-23 06:45

from django.db import migrations, models
import questions.enums


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default=questions.enums.StatusEnum('Pending'), max_length=10),
        ),
    ]
