# Generated by Django 2.2.1 on 2019-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_addimage_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
