# Generated by Django 2.2.1 on 2019-05-17 17:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190507_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
